#ifndef COMPAT_BIT_OPS_H
#define COMPAT_BIT_OPS_H

#include_next <linux/bitops.h>

/* Include the autogenerated header file */
#include "../../compat/config.h"

#ifndef BIT_ULL
#define BIT_ULL(nr)    (1ULL << (nr))
#endif

#endif /* COMPAT_BIT_OPS_H */
