#ifndef COMPAT_RCULIST_H
#define COMPAT_RCULIST_H

#include_next <linux/rculist.h>

/* Include the autogenerated header file */
#include "../../compat/config.h"

#ifdef HAVE_HLIST_FOR_EACH_ENTRY_3_PARAMS
#define compat_hlist_for_each_entry_rcu(pos, head, member) \
	hlist_for_each_entry_rcu(pos, head, member)

#else
#define compat_hlist_for_each_entry_rcu(pos, head, member) \
	hlist_for_each_entry_rcu(pos, hlnode, head, member)

#endif

#endif /* COMPAT_RCULIST_H */
